//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldClientApp.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/wcfOldService")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IPerson")]
    public interface IPerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetPersons", ReplyAction="http://tempuri.org/IPerson/GetPersonsResponse")]
        OldClientApp.ServiceRef.Person[] GetPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetPersons", ReplyAction="http://tempuri.org/IPerson/GetPersonsResponse")]
        System.Threading.Tasks.Task<OldClientApp.ServiceRef.Person[]> GetPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetPerson", ReplyAction="http://tempuri.org/IPerson/GetPersonResponse")]
        OldClientApp.ServiceRef.Person GetPerson(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetPerson", ReplyAction="http://tempuri.org/IPerson/GetPersonResponse")]
        System.Threading.Tasks.Task<OldClientApp.ServiceRef.Person> GetPersonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/AddPerson", ReplyAction="http://tempuri.org/IPerson/AddPersonResponse")]
        void AddPerson(OldClientApp.ServiceRef.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/AddPerson", ReplyAction="http://tempuri.org/IPerson/AddPersonResponse")]
        System.Threading.Tasks.Task AddPersonAsync(OldClientApp.ServiceRef.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/ModifyPerson", ReplyAction="http://tempuri.org/IPerson/ModifyPersonResponse")]
        void ModifyPerson(OldClientApp.ServiceRef.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/ModifyPerson", ReplyAction="http://tempuri.org/IPerson/ModifyPersonResponse")]
        System.Threading.Tasks.Task ModifyPersonAsync(OldClientApp.ServiceRef.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetArraySize", ReplyAction="http://tempuri.org/IPerson/GetArraySizeResponse")]
        int GetArraySize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerson/GetArraySize", ReplyAction="http://tempuri.org/IPerson/GetArraySizeResponse")]
        System.Threading.Tasks.Task<int> GetArraySizeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonChannel : OldClientApp.ServiceRef.IPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonClient : System.ServiceModel.ClientBase<OldClientApp.ServiceRef.IPerson>, OldClientApp.ServiceRef.IPerson {
        
        public PersonClient() {
        }
        
        public PersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OldClientApp.ServiceRef.Person[] GetPersons() {
            return base.Channel.GetPersons();
        }
        
        public System.Threading.Tasks.Task<OldClientApp.ServiceRef.Person[]> GetPersonsAsync() {
            return base.Channel.GetPersonsAsync();
        }
        
        public OldClientApp.ServiceRef.Person GetPerson(int id) {
            return base.Channel.GetPerson(id);
        }
        
        public System.Threading.Tasks.Task<OldClientApp.ServiceRef.Person> GetPersonAsync(int id) {
            return base.Channel.GetPersonAsync(id);
        }
        
        public void AddPerson(OldClientApp.ServiceRef.Person person) {
            base.Channel.AddPerson(person);
        }
        
        public System.Threading.Tasks.Task AddPersonAsync(OldClientApp.ServiceRef.Person person) {
            return base.Channel.AddPersonAsync(person);
        }
        
        public void ModifyPerson(OldClientApp.ServiceRef.Person person) {
            base.Channel.ModifyPerson(person);
        }
        
        public System.Threading.Tasks.Task ModifyPersonAsync(OldClientApp.ServiceRef.Person person) {
            return base.Channel.ModifyPersonAsync(person);
        }
        
        public int GetArraySize() {
            return base.Channel.GetArraySize();
        }
        
        public System.Threading.Tasks.Task<int> GetArraySizeAsync() {
            return base.Channel.GetArraySizeAsync();
        }
    }
}
